auto_save: false
display_label_popup: true
store_data: true
keep_prev: false
keep_prev_scale: false
keep_prev_brightness: false
keep_prev_contrast: false
logger_level: info

grades: null
products: null
flags: null
label_flags: null
labels: null
file_search: null
sort_labels: true
validate_label: null

default_shape_color: [0, 255, 0]
shape_color: auto  # null, 'auto', 'manual'
shift_auto_shape_color: 0
label_colors: null

# lang of labelme
local_lang: null

shape:
  # drawing
  line_color: [0, 255, 0, 128]
  fill_color: [0, 255, 0, 0]  # transparent
  vertex_fill_color: [0, 255, 0, 255]
  # selecting / hovering
  select_line_color: [255, 255, 255, 255]
  select_fill_color: [0, 255, 0, 155]
  hvertex_fill_color: [255, 255, 255, 255]
  point_size: 8

# main
grades_dock:
  show: true
  closable: true
  movable: true
  floatable: true
products_dock:
  show: true
  closable: true
  movable: true
  floatable: true
flag_dock:
  show: false
  closable: true
  movable: true
  floatable: true
label_dock:
  show: false
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

# canvas
epsilon: 10.0
canvas:
  # None: do nothing
  # close: close polygon
  double_click: close
  # The max number of edits we can undo
  num_backups: 10

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  saveAuto: Ctrl+A
  save_to: Ctrl+Shift+C
  delete_file: Ctrl+Delete

  open_next: Ctrl+N
  open_prev: Ctrl+P

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  create_polygon: Ctrl+1
  create_rectangle: Ctrl+2
  create_circle: Ctrl+3
  create_line: Ctrl+4
  create_point: Ctrl+5
  create_linestrip: null
  edit_polygon: Ctrl+J
  delete_polygon: Delete
  duplicate_polygon: Ctrl+D
  copy_polygon: Ctrl+C
  paste_polygon: Ctrl+V
  undo: Ctrl+Z
  undo_last_point: Ctrl+Y
  add_point_to_edge: Ctrl+Shift+P
  edit_label: Ctrl+E
  toggle_keep_prev_mode: Ctrl+P
  remove_selected_point: Ctrl+M
  tutorial: Alt+H
  changepwd: Alt+C
  hideAll: Alt+9
  showAll: Alt+0
  brightness_contrast: Ctrl+B
  trans: Ctrl+X
  cursorArrow: Ctrl+7

app_version: 20220927